# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
    ]
